-- Create "request_logs" table
CREATE TABLE "request_logs" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "method" character varying NOT NULL,
  "path" character varying NOT NULL,
  "headers" text NULL,
  "body" text NULL,
  "ip" character varying NULL,
  "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);
