// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sync"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/echo-logger/service/ent/predicate"
	"github.com/echo-logger/service/ent/requestlog"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeRequestLog = "RequestLog"
)

// RequestLogMutation represents an operation that mutates the RequestLog nodes in the graph.
type RequestLogMutation struct {
	config
	op            Op
	typ           string
	id            *int
	method        *string
	_path         *string
	headers       *string
	body          *string
	ip            *string
	created_at    *time.Time
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*RequestLog, error)
	predicates    []predicate.RequestLog
}

var _ ent.Mutation = (*RequestLogMutation)(nil)

// requestlogOption allows management of the mutation configuration using functional options.
type requestlogOption func(*RequestLogMutation)

// newRequestLogMutation creates new mutation for the RequestLog entity.
func newRequestLogMutation(c config, op Op, opts ...requestlogOption) *RequestLogMutation {
	m := &RequestLogMutation{
		config:        c,
		op:            op,
		typ:           TypeRequestLog,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withRequestLogID sets the ID field of the mutation.
func withRequestLogID(id int) requestlogOption {
	return func(m *RequestLogMutation) {
		var (
			err   error
			once  sync.Once
			value *RequestLog
		)
		m.oldValue = func(ctx context.Context) (*RequestLog, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().RequestLog.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withRequestLog sets the old RequestLog of the mutation.
func withRequestLog(node *RequestLog) requestlogOption {
	return func(m *RequestLogMutation) {
		m.oldValue = func(context.Context) (*RequestLog, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m RequestLogMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m RequestLogMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *RequestLogMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *RequestLogMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().RequestLog.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetMethod sets the "method" field.
func (m *RequestLogMutation) SetMethod(s string) {
	m.method = &s
}

// Method returns the value of the "method" field in the mutation.
func (m *RequestLogMutation) Method() (r string, exists bool) {
	v := m.method
	if v == nil {
		return
	}
	return *v, true
}

// OldMethod returns the old "method" field's value of the RequestLog entity.
// If the RequestLog object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RequestLogMutation) OldMethod(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldMethod is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldMethod requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldMethod: %w", err)
	}
	return oldValue.Method, nil
}

// ResetMethod resets all changes to the "method" field.
func (m *RequestLogMutation) ResetMethod() {
	m.method = nil
}

// SetPath sets the "path" field.
func (m *RequestLogMutation) SetPath(s string) {
	m._path = &s
}

// Path returns the value of the "path" field in the mutation.
func (m *RequestLogMutation) Path() (r string, exists bool) {
	v := m._path
	if v == nil {
		return
	}
	return *v, true
}

// OldPath returns the old "path" field's value of the RequestLog entity.
// If the RequestLog object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RequestLogMutation) OldPath(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPath is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPath requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPath: %w", err)
	}
	return oldValue.Path, nil
}

// ResetPath resets all changes to the "path" field.
func (m *RequestLogMutation) ResetPath() {
	m._path = nil
}

// SetHeaders sets the "headers" field.
func (m *RequestLogMutation) SetHeaders(s string) {
	m.headers = &s
}

// Headers returns the value of the "headers" field in the mutation.
func (m *RequestLogMutation) Headers() (r string, exists bool) {
	v := m.headers
	if v == nil {
		return
	}
	return *v, true
}

// OldHeaders returns the old "headers" field's value of the RequestLog entity.
// If the RequestLog object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RequestLogMutation) OldHeaders(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldHeaders is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldHeaders requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldHeaders: %w", err)
	}
	return oldValue.Headers, nil
}

// ClearHeaders clears the value of the "headers" field.
func (m *RequestLogMutation) ClearHeaders() {
	m.headers = nil
	m.clearedFields[requestlog.FieldHeaders] = struct{}{}
}

// HeadersCleared returns if the "headers" field was cleared in this mutation.
func (m *RequestLogMutation) HeadersCleared() bool {
	_, ok := m.clearedFields[requestlog.FieldHeaders]
	return ok
}

// ResetHeaders resets all changes to the "headers" field.
func (m *RequestLogMutation) ResetHeaders() {
	m.headers = nil
	delete(m.clearedFields, requestlog.FieldHeaders)
}

// SetBody sets the "body" field.
func (m *RequestLogMutation) SetBody(s string) {
	m.body = &s
}

// Body returns the value of the "body" field in the mutation.
func (m *RequestLogMutation) Body() (r string, exists bool) {
	v := m.body
	if v == nil {
		return
	}
	return *v, true
}

// OldBody returns the old "body" field's value of the RequestLog entity.
// If the RequestLog object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RequestLogMutation) OldBody(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldBody is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldBody requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldBody: %w", err)
	}
	return oldValue.Body, nil
}

// ClearBody clears the value of the "body" field.
func (m *RequestLogMutation) ClearBody() {
	m.body = nil
	m.clearedFields[requestlog.FieldBody] = struct{}{}
}

// BodyCleared returns if the "body" field was cleared in this mutation.
func (m *RequestLogMutation) BodyCleared() bool {
	_, ok := m.clearedFields[requestlog.FieldBody]
	return ok
}

// ResetBody resets all changes to the "body" field.
func (m *RequestLogMutation) ResetBody() {
	m.body = nil
	delete(m.clearedFields, requestlog.FieldBody)
}

// SetIP sets the "ip" field.
func (m *RequestLogMutation) SetIP(s string) {
	m.ip = &s
}

// IP returns the value of the "ip" field in the mutation.
func (m *RequestLogMutation) IP() (r string, exists bool) {
	v := m.ip
	if v == nil {
		return
	}
	return *v, true
}

// OldIP returns the old "ip" field's value of the RequestLog entity.
// If the RequestLog object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RequestLogMutation) OldIP(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldIP is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldIP requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldIP: %w", err)
	}
	return oldValue.IP, nil
}

// ClearIP clears the value of the "ip" field.
func (m *RequestLogMutation) ClearIP() {
	m.ip = nil
	m.clearedFields[requestlog.FieldIP] = struct{}{}
}

// IPCleared returns if the "ip" field was cleared in this mutation.
func (m *RequestLogMutation) IPCleared() bool {
	_, ok := m.clearedFields[requestlog.FieldIP]
	return ok
}

// ResetIP resets all changes to the "ip" field.
func (m *RequestLogMutation) ResetIP() {
	m.ip = nil
	delete(m.clearedFields, requestlog.FieldIP)
}

// SetCreatedAt sets the "created_at" field.
func (m *RequestLogMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *RequestLogMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the RequestLog entity.
// If the RequestLog object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RequestLogMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *RequestLogMutation) ResetCreatedAt() {
	m.created_at = nil
}

// Where appends a list predicates to the RequestLogMutation builder.
func (m *RequestLogMutation) Where(ps ...predicate.RequestLog) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the RequestLogMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *RequestLogMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.RequestLog, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *RequestLogMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *RequestLogMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (RequestLog).
func (m *RequestLogMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *RequestLogMutation) Fields() []string {
	fields := make([]string, 0, 6)
	if m.method != nil {
		fields = append(fields, requestlog.FieldMethod)
	}
	if m._path != nil {
		fields = append(fields, requestlog.FieldPath)
	}
	if m.headers != nil {
		fields = append(fields, requestlog.FieldHeaders)
	}
	if m.body != nil {
		fields = append(fields, requestlog.FieldBody)
	}
	if m.ip != nil {
		fields = append(fields, requestlog.FieldIP)
	}
	if m.created_at != nil {
		fields = append(fields, requestlog.FieldCreatedAt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *RequestLogMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case requestlog.FieldMethod:
		return m.Method()
	case requestlog.FieldPath:
		return m.Path()
	case requestlog.FieldHeaders:
		return m.Headers()
	case requestlog.FieldBody:
		return m.Body()
	case requestlog.FieldIP:
		return m.IP()
	case requestlog.FieldCreatedAt:
		return m.CreatedAt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *RequestLogMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case requestlog.FieldMethod:
		return m.OldMethod(ctx)
	case requestlog.FieldPath:
		return m.OldPath(ctx)
	case requestlog.FieldHeaders:
		return m.OldHeaders(ctx)
	case requestlog.FieldBody:
		return m.OldBody(ctx)
	case requestlog.FieldIP:
		return m.OldIP(ctx)
	case requestlog.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	}
	return nil, fmt.Errorf("unknown RequestLog field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *RequestLogMutation) SetField(name string, value ent.Value) error {
	switch name {
	case requestlog.FieldMethod:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetMethod(v)
		return nil
	case requestlog.FieldPath:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPath(v)
		return nil
	case requestlog.FieldHeaders:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetHeaders(v)
		return nil
	case requestlog.FieldBody:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetBody(v)
		return nil
	case requestlog.FieldIP:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetIP(v)
		return nil
	case requestlog.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	}
	return fmt.Errorf("unknown RequestLog field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *RequestLogMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *RequestLogMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *RequestLogMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown RequestLog numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *RequestLogMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(requestlog.FieldHeaders) {
		fields = append(fields, requestlog.FieldHeaders)
	}
	if m.FieldCleared(requestlog.FieldBody) {
		fields = append(fields, requestlog.FieldBody)
	}
	if m.FieldCleared(requestlog.FieldIP) {
		fields = append(fields, requestlog.FieldIP)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *RequestLogMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *RequestLogMutation) ClearField(name string) error {
	switch name {
	case requestlog.FieldHeaders:
		m.ClearHeaders()
		return nil
	case requestlog.FieldBody:
		m.ClearBody()
		return nil
	case requestlog.FieldIP:
		m.ClearIP()
		return nil
	}
	return fmt.Errorf("unknown RequestLog nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *RequestLogMutation) ResetField(name string) error {
	switch name {
	case requestlog.FieldMethod:
		m.ResetMethod()
		return nil
	case requestlog.FieldPath:
		m.ResetPath()
		return nil
	case requestlog.FieldHeaders:
		m.ResetHeaders()
		return nil
	case requestlog.FieldBody:
		m.ResetBody()
		return nil
	case requestlog.FieldIP:
		m.ResetIP()
		return nil
	case requestlog.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	}
	return fmt.Errorf("unknown RequestLog field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *RequestLogMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *RequestLogMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *RequestLogMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *RequestLogMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *RequestLogMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *RequestLogMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *RequestLogMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown RequestLog unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *RequestLogMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown RequestLog edge %s", name)
}
