// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/echo-logger/service/ent/requestlog"
)

// RequestLog is the model entity for the RequestLog schema.
type RequestLog struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// HTTP method (GET, POST, etc.)
	Method string `json:"method,omitempty"`
	// Request path
	Path string `json:"path,omitempty"`
	// Request headers as JSON string
	Headers string `json:"headers,omitempty"`
	// Request body
	Body string `json:"body,omitempty"`
	// Client IP address
	IP string `json:"ip,omitempty"`
	// Timestamp of the request
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Timestamp of the request
	JopaTime     time.Time `json:"jopa_time,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*RequestLog) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case requestlog.FieldID:
			values[i] = new(sql.NullInt64)
		case requestlog.FieldMethod, requestlog.FieldPath, requestlog.FieldHeaders, requestlog.FieldBody, requestlog.FieldIP:
			values[i] = new(sql.NullString)
		case requestlog.FieldCreatedAt, requestlog.FieldJopaTime:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the RequestLog fields.
func (_m *RequestLog) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case requestlog.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case requestlog.FieldMethod:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field method", values[i])
			} else if value.Valid {
				_m.Method = value.String
			}
		case requestlog.FieldPath:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field path", values[i])
			} else if value.Valid {
				_m.Path = value.String
			}
		case requestlog.FieldHeaders:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field headers", values[i])
			} else if value.Valid {
				_m.Headers = value.String
			}
		case requestlog.FieldBody:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field body", values[i])
			} else if value.Valid {
				_m.Body = value.String
			}
		case requestlog.FieldIP:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ip", values[i])
			} else if value.Valid {
				_m.IP = value.String
			}
		case requestlog.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case requestlog.FieldJopaTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field jopa_time", values[i])
			} else if value.Valid {
				_m.JopaTime = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the RequestLog.
// This includes values selected through modifiers, order, etc.
func (_m *RequestLog) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this RequestLog.
// Note that you need to call RequestLog.Unwrap() before calling this method if this RequestLog
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *RequestLog) Update() *RequestLogUpdateOne {
	return NewRequestLogClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the RequestLog entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *RequestLog) Unwrap() *RequestLog {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: RequestLog is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *RequestLog) String() string {
	var builder strings.Builder
	builder.WriteString("RequestLog(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("method=")
	builder.WriteString(_m.Method)
	builder.WriteString(", ")
	builder.WriteString("path=")
	builder.WriteString(_m.Path)
	builder.WriteString(", ")
	builder.WriteString("headers=")
	builder.WriteString(_m.Headers)
	builder.WriteString(", ")
	builder.WriteString("body=")
	builder.WriteString(_m.Body)
	builder.WriteString(", ")
	builder.WriteString("ip=")
	builder.WriteString(_m.IP)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("jopa_time=")
	builder.WriteString(_m.JopaTime.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// RequestLogs is a parsable slice of RequestLog.
type RequestLogs []*RequestLog
