// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/echo-logger/service/ent/requestlog"
)

// RequestLogCreate is the builder for creating a RequestLog entity.
type RequestLogCreate struct {
	config
	mutation *RequestLogMutation
	hooks    []Hook
}

// SetMethod sets the "method" field.
func (_c *RequestLogCreate) SetMethod(v string) *RequestLogCreate {
	_c.mutation.SetMethod(v)
	return _c
}

// SetPath sets the "path" field.
func (_c *RequestLogCreate) SetPath(v string) *RequestLogCreate {
	_c.mutation.SetPath(v)
	return _c
}

// SetHeaders sets the "headers" field.
func (_c *RequestLogCreate) SetHeaders(v string) *RequestLogCreate {
	_c.mutation.SetHeaders(v)
	return _c
}

// SetNillableHeaders sets the "headers" field if the given value is not nil.
func (_c *RequestLogCreate) SetNillableHeaders(v *string) *RequestLogCreate {
	if v != nil {
		_c.SetHeaders(*v)
	}
	return _c
}

// SetBody sets the "body" field.
func (_c *RequestLogCreate) SetBody(v string) *RequestLogCreate {
	_c.mutation.SetBody(v)
	return _c
}

// SetNillableBody sets the "body" field if the given value is not nil.
func (_c *RequestLogCreate) SetNillableBody(v *string) *RequestLogCreate {
	if v != nil {
		_c.SetBody(*v)
	}
	return _c
}

// SetIP sets the "ip" field.
func (_c *RequestLogCreate) SetIP(v string) *RequestLogCreate {
	_c.mutation.SetIP(v)
	return _c
}

// SetNillableIP sets the "ip" field if the given value is not nil.
func (_c *RequestLogCreate) SetNillableIP(v *string) *RequestLogCreate {
	if v != nil {
		_c.SetIP(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *RequestLogCreate) SetCreatedAt(v time.Time) *RequestLogCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *RequestLogCreate) SetNillableCreatedAt(v *time.Time) *RequestLogCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// Mutation returns the RequestLogMutation object of the builder.
func (_c *RequestLogCreate) Mutation() *RequestLogMutation {
	return _c.mutation
}

// Save creates the RequestLog in the database.
func (_c *RequestLogCreate) Save(ctx context.Context) (*RequestLog, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RequestLogCreate) SaveX(ctx context.Context) *RequestLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RequestLogCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RequestLogCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *RequestLogCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := requestlog.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RequestLogCreate) check() error {
	if _, ok := _c.mutation.Method(); !ok {
		return &ValidationError{Name: "method", err: errors.New(`ent: missing required field "RequestLog.method"`)}
	}
	if v, ok := _c.mutation.Method(); ok {
		if err := requestlog.MethodValidator(v); err != nil {
			return &ValidationError{Name: "method", err: fmt.Errorf(`ent: validator failed for field "RequestLog.method": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Path(); !ok {
		return &ValidationError{Name: "path", err: errors.New(`ent: missing required field "RequestLog.path"`)}
	}
	if v, ok := _c.mutation.Path(); ok {
		if err := requestlog.PathValidator(v); err != nil {
			return &ValidationError{Name: "path", err: fmt.Errorf(`ent: validator failed for field "RequestLog.path": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "RequestLog.created_at"`)}
	}
	return nil
}

func (_c *RequestLogCreate) sqlSave(ctx context.Context) (*RequestLog, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RequestLogCreate) createSpec() (*RequestLog, *sqlgraph.CreateSpec) {
	var (
		_node = &RequestLog{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(requestlog.Table, sqlgraph.NewFieldSpec(requestlog.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Method(); ok {
		_spec.SetField(requestlog.FieldMethod, field.TypeString, value)
		_node.Method = value
	}
	if value, ok := _c.mutation.Path(); ok {
		_spec.SetField(requestlog.FieldPath, field.TypeString, value)
		_node.Path = value
	}
	if value, ok := _c.mutation.Headers(); ok {
		_spec.SetField(requestlog.FieldHeaders, field.TypeString, value)
		_node.Headers = value
	}
	if value, ok := _c.mutation.Body(); ok {
		_spec.SetField(requestlog.FieldBody, field.TypeString, value)
		_node.Body = value
	}
	if value, ok := _c.mutation.IP(); ok {
		_spec.SetField(requestlog.FieldIP, field.TypeString, value)
		_node.IP = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(requestlog.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// RequestLogCreateBulk is the builder for creating many RequestLog entities in bulk.
type RequestLogCreateBulk struct {
	config
	err      error
	builders []*RequestLogCreate
}

// Save creates the RequestLog entities in the database.
func (_c *RequestLogCreateBulk) Save(ctx context.Context) ([]*RequestLog, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*RequestLog, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RequestLogMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RequestLogCreateBulk) SaveX(ctx context.Context) []*RequestLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RequestLogCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RequestLogCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
