// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/echo-logger/service/ent/predicate"
	"github.com/echo-logger/service/ent/requestlog"
)

// RequestLogUpdate is the builder for updating RequestLog entities.
type RequestLogUpdate struct {
	config
	hooks    []Hook
	mutation *RequestLogMutation
}

// Where appends a list predicates to the RequestLogUpdate builder.
func (_u *RequestLogUpdate) Where(ps ...predicate.RequestLog) *RequestLogUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetMethod sets the "method" field.
func (_u *RequestLogUpdate) SetMethod(v string) *RequestLogUpdate {
	_u.mutation.SetMethod(v)
	return _u
}

// SetNillableMethod sets the "method" field if the given value is not nil.
func (_u *RequestLogUpdate) SetNillableMethod(v *string) *RequestLogUpdate {
	if v != nil {
		_u.SetMethod(*v)
	}
	return _u
}

// SetPath sets the "path" field.
func (_u *RequestLogUpdate) SetPath(v string) *RequestLogUpdate {
	_u.mutation.SetPath(v)
	return _u
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (_u *RequestLogUpdate) SetNillablePath(v *string) *RequestLogUpdate {
	if v != nil {
		_u.SetPath(*v)
	}
	return _u
}

// SetHeaders sets the "headers" field.
func (_u *RequestLogUpdate) SetHeaders(v string) *RequestLogUpdate {
	_u.mutation.SetHeaders(v)
	return _u
}

// SetNillableHeaders sets the "headers" field if the given value is not nil.
func (_u *RequestLogUpdate) SetNillableHeaders(v *string) *RequestLogUpdate {
	if v != nil {
		_u.SetHeaders(*v)
	}
	return _u
}

// ClearHeaders clears the value of the "headers" field.
func (_u *RequestLogUpdate) ClearHeaders() *RequestLogUpdate {
	_u.mutation.ClearHeaders()
	return _u
}

// SetBody sets the "body" field.
func (_u *RequestLogUpdate) SetBody(v string) *RequestLogUpdate {
	_u.mutation.SetBody(v)
	return _u
}

// SetNillableBody sets the "body" field if the given value is not nil.
func (_u *RequestLogUpdate) SetNillableBody(v *string) *RequestLogUpdate {
	if v != nil {
		_u.SetBody(*v)
	}
	return _u
}

// ClearBody clears the value of the "body" field.
func (_u *RequestLogUpdate) ClearBody() *RequestLogUpdate {
	_u.mutation.ClearBody()
	return _u
}

// SetIP sets the "ip" field.
func (_u *RequestLogUpdate) SetIP(v string) *RequestLogUpdate {
	_u.mutation.SetIP(v)
	return _u
}

// SetNillableIP sets the "ip" field if the given value is not nil.
func (_u *RequestLogUpdate) SetNillableIP(v *string) *RequestLogUpdate {
	if v != nil {
		_u.SetIP(*v)
	}
	return _u
}

// ClearIP clears the value of the "ip" field.
func (_u *RequestLogUpdate) ClearIP() *RequestLogUpdate {
	_u.mutation.ClearIP()
	return _u
}

// Mutation returns the RequestLogMutation object of the builder.
func (_u *RequestLogUpdate) Mutation() *RequestLogMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RequestLogUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RequestLogUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RequestLogUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RequestLogUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RequestLogUpdate) check() error {
	if v, ok := _u.mutation.Method(); ok {
		if err := requestlog.MethodValidator(v); err != nil {
			return &ValidationError{Name: "method", err: fmt.Errorf(`ent: validator failed for field "RequestLog.method": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Path(); ok {
		if err := requestlog.PathValidator(v); err != nil {
			return &ValidationError{Name: "path", err: fmt.Errorf(`ent: validator failed for field "RequestLog.path": %w`, err)}
		}
	}
	return nil
}

func (_u *RequestLogUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(requestlog.Table, requestlog.Columns, sqlgraph.NewFieldSpec(requestlog.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Method(); ok {
		_spec.SetField(requestlog.FieldMethod, field.TypeString, value)
	}
	if value, ok := _u.mutation.Path(); ok {
		_spec.SetField(requestlog.FieldPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.Headers(); ok {
		_spec.SetField(requestlog.FieldHeaders, field.TypeString, value)
	}
	if _u.mutation.HeadersCleared() {
		_spec.ClearField(requestlog.FieldHeaders, field.TypeString)
	}
	if value, ok := _u.mutation.Body(); ok {
		_spec.SetField(requestlog.FieldBody, field.TypeString, value)
	}
	if _u.mutation.BodyCleared() {
		_spec.ClearField(requestlog.FieldBody, field.TypeString)
	}
	if value, ok := _u.mutation.IP(); ok {
		_spec.SetField(requestlog.FieldIP, field.TypeString, value)
	}
	if _u.mutation.IPCleared() {
		_spec.ClearField(requestlog.FieldIP, field.TypeString)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{requestlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RequestLogUpdateOne is the builder for updating a single RequestLog entity.
type RequestLogUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RequestLogMutation
}

// SetMethod sets the "method" field.
func (_u *RequestLogUpdateOne) SetMethod(v string) *RequestLogUpdateOne {
	_u.mutation.SetMethod(v)
	return _u
}

// SetNillableMethod sets the "method" field if the given value is not nil.
func (_u *RequestLogUpdateOne) SetNillableMethod(v *string) *RequestLogUpdateOne {
	if v != nil {
		_u.SetMethod(*v)
	}
	return _u
}

// SetPath sets the "path" field.
func (_u *RequestLogUpdateOne) SetPath(v string) *RequestLogUpdateOne {
	_u.mutation.SetPath(v)
	return _u
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (_u *RequestLogUpdateOne) SetNillablePath(v *string) *RequestLogUpdateOne {
	if v != nil {
		_u.SetPath(*v)
	}
	return _u
}

// SetHeaders sets the "headers" field.
func (_u *RequestLogUpdateOne) SetHeaders(v string) *RequestLogUpdateOne {
	_u.mutation.SetHeaders(v)
	return _u
}

// SetNillableHeaders sets the "headers" field if the given value is not nil.
func (_u *RequestLogUpdateOne) SetNillableHeaders(v *string) *RequestLogUpdateOne {
	if v != nil {
		_u.SetHeaders(*v)
	}
	return _u
}

// ClearHeaders clears the value of the "headers" field.
func (_u *RequestLogUpdateOne) ClearHeaders() *RequestLogUpdateOne {
	_u.mutation.ClearHeaders()
	return _u
}

// SetBody sets the "body" field.
func (_u *RequestLogUpdateOne) SetBody(v string) *RequestLogUpdateOne {
	_u.mutation.SetBody(v)
	return _u
}

// SetNillableBody sets the "body" field if the given value is not nil.
func (_u *RequestLogUpdateOne) SetNillableBody(v *string) *RequestLogUpdateOne {
	if v != nil {
		_u.SetBody(*v)
	}
	return _u
}

// ClearBody clears the value of the "body" field.
func (_u *RequestLogUpdateOne) ClearBody() *RequestLogUpdateOne {
	_u.mutation.ClearBody()
	return _u
}

// SetIP sets the "ip" field.
func (_u *RequestLogUpdateOne) SetIP(v string) *RequestLogUpdateOne {
	_u.mutation.SetIP(v)
	return _u
}

// SetNillableIP sets the "ip" field if the given value is not nil.
func (_u *RequestLogUpdateOne) SetNillableIP(v *string) *RequestLogUpdateOne {
	if v != nil {
		_u.SetIP(*v)
	}
	return _u
}

// ClearIP clears the value of the "ip" field.
func (_u *RequestLogUpdateOne) ClearIP() *RequestLogUpdateOne {
	_u.mutation.ClearIP()
	return _u
}

// Mutation returns the RequestLogMutation object of the builder.
func (_u *RequestLogUpdateOne) Mutation() *RequestLogMutation {
	return _u.mutation
}

// Where appends a list predicates to the RequestLogUpdate builder.
func (_u *RequestLogUpdateOne) Where(ps ...predicate.RequestLog) *RequestLogUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RequestLogUpdateOne) Select(field string, fields ...string) *RequestLogUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated RequestLog entity.
func (_u *RequestLogUpdateOne) Save(ctx context.Context) (*RequestLog, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RequestLogUpdateOne) SaveX(ctx context.Context) *RequestLog {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RequestLogUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RequestLogUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RequestLogUpdateOne) check() error {
	if v, ok := _u.mutation.Method(); ok {
		if err := requestlog.MethodValidator(v); err != nil {
			return &ValidationError{Name: "method", err: fmt.Errorf(`ent: validator failed for field "RequestLog.method": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Path(); ok {
		if err := requestlog.PathValidator(v); err != nil {
			return &ValidationError{Name: "path", err: fmt.Errorf(`ent: validator failed for field "RequestLog.path": %w`, err)}
		}
	}
	return nil
}

func (_u *RequestLogUpdateOne) sqlSave(ctx context.Context) (_node *RequestLog, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(requestlog.Table, requestlog.Columns, sqlgraph.NewFieldSpec(requestlog.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RequestLog.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, requestlog.FieldID)
		for _, f := range fields {
			if !requestlog.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != requestlog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Method(); ok {
		_spec.SetField(requestlog.FieldMethod, field.TypeString, value)
	}
	if value, ok := _u.mutation.Path(); ok {
		_spec.SetField(requestlog.FieldPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.Headers(); ok {
		_spec.SetField(requestlog.FieldHeaders, field.TypeString, value)
	}
	if _u.mutation.HeadersCleared() {
		_spec.ClearField(requestlog.FieldHeaders, field.TypeString)
	}
	if value, ok := _u.mutation.Body(); ok {
		_spec.SetField(requestlog.FieldBody, field.TypeString, value)
	}
	if _u.mutation.BodyCleared() {
		_spec.ClearField(requestlog.FieldBody, field.TypeString)
	}
	if value, ok := _u.mutation.IP(); ok {
		_spec.SetField(requestlog.FieldIP, field.TypeString, value)
	}
	if _u.mutation.IPCleared() {
		_spec.ClearField(requestlog.FieldIP, field.TypeString)
	}
	_node = &RequestLog{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{requestlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
