// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/echo-logger/service/ent/requestlog"
	"github.com/echo-logger/service/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	requestlogFields := schema.RequestLog{}.Fields()
	_ = requestlogFields
	// requestlogDescMethod is the schema descriptor for method field.
	requestlogDescMethod := requestlogFields[0].Descriptor()
	// requestlog.MethodValidator is a validator for the "method" field. It is called by the builders before save.
	requestlog.MethodValidator = requestlogDescMethod.Validators[0].(func(string) error)
	// requestlogDescPath is the schema descriptor for path field.
	requestlogDescPath := requestlogFields[1].Descriptor()
	// requestlog.PathValidator is a validator for the "path" field. It is called by the builders before save.
	requestlog.PathValidator = requestlogDescPath.Validators[0].(func(string) error)
	// requestlogDescCreatedAt is the schema descriptor for created_at field.
	requestlogDescCreatedAt := requestlogFields[5].Descriptor()
	// requestlog.DefaultCreatedAt holds the default value on creation for the created_at field.
	requestlog.DefaultCreatedAt = requestlogDescCreatedAt.Default.(func() time.Time)
}
